import { AlertTriangle, CheckCircle2, Search, Sparkles, ShieldCheck, Target, Copy } from 'lucide-react'
import Card from '@/components/common/Card'
import Badge from '@/components/common/Badge'
import EmptyState from '@/components/common/EmptyState'
import ProgressBar from '@/components/common/ProgressBar'
import Skeleton from '@/components/common/Skeleton'
import Spinner from '@/components/common/Spinner'
import { useAppSelector } from '@/redux/hooks'
import { riskTone, severityTone } from '@/utils/badgeTone'
import { formatPercentage } from '@/utils/formatters'

function RiskAssessmentCard() {
  const { complaint, riskAssessment, summary, completeness, rootCause, capa, duplicateProbability, status } =
    useAppSelector((state) => state.complaint)

  const hasComplaint = Boolean(complaint.id)
  const isInitialLoad = status === 'loading' && !hasComplaint
  const isUpdating = status === 'loading' && hasComplaint

  const duplicatePercent = Math.round(duplicateProbability * 100)
  const duplicateTone = duplicatePercent >= 60 ? 'rose' : duplicatePercent >= 30 ? 'amber' : 'emerald'

  return (
    <Card
      title="AI Risk Assessment"
      subtitle="Generated by Groq · gemma2-9b-it"
      icon={Sparkles}
      bodyClassName="space-y-5 p-5"
      actions={
        isUpdating ? (
          <span className="flex items-center gap-1.5 text-xs font-medium text-blue-600">
            <Spinner size={13} />
            Analyzing…
          </span>
        ) : undefined
      }
    >
      {isInitialLoad ? (
        <div className="space-y-5" aria-busy="true" aria-label="Loading risk assessment">
          <div>
            <Skeleton className="mb-2 h-3 w-16" />
            <Skeleton className="h-4 w-full" />
            <Skeleton className="mt-1.5 h-4 w-3/4" />
          </div>
          <div className="flex gap-2">
            <Skeleton className="h-6 w-24 rounded-full" />
            <Skeleton className="h-6 w-24 rounded-full" />
          </div>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <Skeleton className="h-20 w-full" />
            <Skeleton className="h-20 w-full" />
          </div>
        </div>
      ) : !hasComplaint ? (
        <EmptyState
          icon={Sparkles}
          title="No AI assessment yet"
          description="Log a complaint via chat or upload a document to generate a risk assessment."
        />
      ) : (
        <>
          <div>
            <p className="mb-2 text-xs font-medium uppercase tracking-wide text-gray-400">Summary</p>
            <p className="break-words text-sm leading-relaxed text-gray-700">{summary || 'No summary generated yet.'}</p>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <Badge
              label={`Risk: ${riskAssessment.riskLevel ?? 'Not Assessed'}`}
              tone={riskTone(riskAssessment.riskLevel)}
            />
            <Badge label={`Severity: ${complaint.severity ?? 'Not Assessed'}`} tone={severityTone(complaint.severity)} />
          </div>
          {riskAssessment.rationale && (
            <p className="break-words text-xs leading-relaxed text-gray-500">{riskAssessment.rationale}</p>
          )}

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <section className="rounded-lg border border-gray-100 bg-gray-50/60 p-3.5">
              <p className="mb-1.5 flex items-center gap-1.5 text-xs font-semibold text-gray-600">
                <Search size={13} strokeWidth={2.25} aria-hidden="true" />
                Root Cause
              </p>
              <p className="break-words text-xs leading-relaxed text-gray-600">{rootCause || 'Pending analysis.'}</p>
            </section>

            <section className="rounded-lg border border-gray-100 bg-gray-50/60 p-3.5">
              <p className="mb-1.5 flex items-center gap-1.5 text-xs font-semibold text-gray-600">
                <ShieldCheck size={13} strokeWidth={2.25} aria-hidden="true" />
                CAPA Recommendation
              </p>
              <p className="break-words text-xs leading-relaxed text-gray-600">{capa || 'Pending recommendation.'}</p>
            </section>
          </div>

          <section className="rounded-lg border border-gray-100 bg-gray-50/60 p-3.5">
            <p className="mb-1.5 flex items-center gap-1.5 text-xs font-semibold text-gray-600">
              <Target size={13} strokeWidth={2.25} aria-hidden="true" />
              Next Action
            </p>
            <p className="break-words text-xs leading-relaxed text-gray-600">{complaint.nextAction || 'No action recommended yet.'}</p>
          </section>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <section>
              <p className="mb-2 flex items-center gap-1.5 text-xs font-semibold text-gray-600">
                {completeness.isComplete ? (
                  <CheckCircle2 size={13} strokeWidth={2.25} className="text-emerald-500" aria-hidden="true" />
                ) : (
                  <AlertTriangle size={13} strokeWidth={2.25} className="text-amber-500" aria-hidden="true" />
                )}
                Completeness Check
              </p>
              {completeness.isComplete ? (
                <p className="text-xs text-emerald-600">All required fields captured.</p>
              ) : (
                <ul className="space-y-1">
                  {(completeness.missingFields ?? []).map((field) => (
                    <li key={field} className="flex items-center gap-1.5 break-words text-xs text-amber-600">
                      <AlertTriangle size={11} strokeWidth={2.25} aria-hidden="true" />
                      {field}
                    </li>
                  ))}
                </ul>
              )}
            </section>

            <section>
              <p className="mb-2 flex items-center justify-between text-xs font-semibold text-gray-600">
                <span className="flex items-center gap-1.5">
                  <Copy size={13} strokeWidth={2.25} aria-hidden="true" />
                  Duplicate Probability
                </span>
                <span className="font-semibold text-gray-800">{formatPercentage(duplicateProbability)}</span>
              </p>
              <ProgressBar percentage={duplicatePercent} tone={duplicateTone} />
            </section>
          </div>
        </>
      )}
    </Card>
  )
}

export default RiskAssessmentCard
